services:
  zephybot:
    image: zephybot
    container_name: zephybot
    restart: unless-stopped
    env_file: 
      - ./.env
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    build:
      context: .